from __future__ import annotations

import os
import mimetypes
from collections.abc import Mapping
from types import MappingProxyType


# This table is intentionally owned by MeshAgent. Do not replace it with
# mimetypes.guess_type() alone: that function varies by operating system and
# reads host mime.types files, so code formats such as Dart are not portable.
MIME_TYPES_BY_EXTENSION: Mapping[str, str] = MappingProxyType(
    {
        # OpenAI Responses file inputs: documents and spreadsheets.
        "pdf": "application/pdf",
        "xla": "application/vnd.ms-excel",
        "xlb": "application/vnd.ms-excel",
        "xlc": "application/vnd.ms-excel",
        "xlm": "application/vnd.ms-excel",
        "xls": "application/vnd.ms-excel",
        "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xlt": "application/vnd.ms-excel",
        "xlw": "application/vnd.ms-excel",
        "csv": "text/csv",
        "tsv": "text/tsv",
        "iif": "text/x-iif",
        "doc": "application/msword",
        "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "dot": "application/msword",
        "odt": "application/vnd.oasis.opendocument.text",
        "rtf": "application/rtf",
        "pages": "application/vnd.apple.pages",
        "gdoc": "application/vnd.google-apps.document",
        "numbers": "application/vnd.apple.iwork",
        "gsheet": "application/vnd.google-apps.spreadsheet",
        "pot": "application/vnd.ms-powerpoint",
        "ppa": "application/vnd.ms-powerpoint",
        "pps": "application/vnd.ms-powerpoint",
        "ppt": "application/vnd.ms-powerpoint",
        "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "pwz": "application/vnd.ms-powerpoint",
        "wiz": "application/vnd.ms-powerpoint",
        "key": "application/vnd.apple.keynote",
        "gslides": "application/vnd.google-apps.presentation",
        # OpenAI Responses file inputs: text and code.
        "asm": "text/x-asm",
        "bat": "text/x-shellscript",
        "c": "text/x-c",
        "cc": "text/x-c++",
        "conf": "text/plain",
        "cpp": "text/x-c++",
        "css": "text/css",
        "cxx": "text/x-c++",
        "def": "text/plain",
        "dic": "text/plain",
        "eml": "message/rfc822",
        "h": "text/x-c",
        "hh": "text/x-c++",
        "htm": "text/html",
        "html": "text/html",
        "ics": "text/calendar",
        "ifb": "text/calendar",
        "in": "text/plain",
        "js": "application/javascript",
        "json": "application/json",
        "ksh": "text/x-shellscript",
        "list": "text/plain",
        "log": "text/plain",
        "markdown": "text/markdown",
        "md": "text/markdown",
        "mht": "message/rfc822",
        "mhtml": "message/rfc822",
        "mime": "message/rfc822",
        "mjs": "application/javascript",
        "nws": "message/rfc822",
        "pl": "text/x-perl",
        "py": "text/x-python",
        "rst": "text/x-rst",
        "s": "text/x-asm",
        "sql": "application/x-sql",
        "srt": "text/srt",
        "text": "text/plain",
        "txt": "text/plain",
        "vcf": "text/x-vcard",
        "vtt": "text/vtt",
        "xml": "text/xml",
        "ts": "application/typescript",
        "tsx": "text/tsx",
        "jsx": "text/jsx",
        "rs": "application/x-rust",
        "ps1": "application/x-powershell",
        "psm1": "application/x-powershell",
        "psd1": "application/x-powershell",
        "diff": "text/x-diff",
        "patch": "text/x-patch",
        "java": "text/x-java",
        "scala": "application/x-scala",
        "php": "text/x-php",
        "rb": "text/x-ruby",
        "sh": "text/x-sh",
        "bash": "text/x-bash",
        "zsh": "text/x-zsh",
        "tex": "text/x-tex",
        "cs": "text/x-csharp",
        "go": "text/x-go",
        "kt": "text/x-kotlin",
        "kts": "text/x-kotlin",
        "swift": "text/x-swift",
        "lua": "text/x-lua",
        "r": "text/x-r",
        "jl": "text/x-julia",
        "pm": "text/x-perl",
        "m": "text/x-objectivec",
        "mm": "text/x-objectivec++",
        "erl": "text/x-erlang",
        "hrl": "text/x-erlang",
        "ex": "text/x-elixir",
        "exs": "text/x-elixir",
        "hs": "text/x-haskell",
        "lhs": "text/x-haskell",
        "clj": "text/x-clojure",
        "cljs": "text/x-clojure",
        "cljc": "text/x-clojure",
        "groovy": "text/x-groovy",
        "dart": "text/x-dart",
        "awk": "text/x-awk",
        "hbs": "text/x-handlebars",
        "handlebars": "text/x-handlebars",
        "mustache": "text/x-mustache",
        "ejs": "text/x-ejs",
        "jinja": "text/x-jinja2",
        "jinja2": "text/x-jinja2",
        "j2": "text/x-jinja2",
        "liquid": "text/x-liquid",
        "erb": "text/x-erb",
        "twig": "text/x-twig",
        "pug": "text/x-pug",
        "jade": "text/x-jade",
        "tmpl": "text/x-tmpl",
        "cmake": "text/x-cmake",
        "dockerfile": "text/x-dockerfile",
        "gradle": "text/x-gradle",
        "ini": "text/x-ini",
        "properties": "text/x-properties",
        "proto": "text/x-protobuf",
        "sass": "text/x-sass",
        "scss": "text/x-scss",
        "less": "text/x-less",
        "hcl": "text/x-hcl",
        "tf": "text/x-terraform",
        "tfvars": "text/x-terraform",
        "toml": "text/x-toml",
        "graphql": "application/graphql",
        "gql": "application/graphql",
        "ndjson": "application/x-ndjson",
        "jsonl": "application/x-ndjson",
        "json5": "application/json5",
        "yaml": "text/x-yaml",
        "yml": "text/x-yaml",
        "astro": "text/x-astro",
        "mk": "text/x-makefile",
        "lisp": "text/x-lisp",
        "lsp": "text/x-lisp",
        "vbs": "text/vbscript",
        "xhtml": "application/xhtml+xml",
        # Common non-OpenAI file types retain the existing tool behavior.
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "jpe": "image/jpeg",
        "gif": "image/gif",
        "webp": "image/webp",
        "bmp": "image/bmp",
        "svg": "image/svg+xml",
        "tif": "image/tiff",
        "tiff": "image/tiff",
        "avif": "image/avif",
        "heic": "image/heic",
        "heif": "image/heif",
        "ico": "image/x-icon",
        "wav": "audio/x-wav",
        "mp3": "audio/mpeg",
        "mp4": "video/mp4",
        "webm": "video/webm",
        "mov": "video/quicktime",
        "zip": "application/zip",
        "tar": "application/x-tar",
        "gz": "application/gzip",
        "bz2": "application/x-bzip2",
        "xz": "application/x-xz",
        "7z": "application/x-7z-compressed",
        "rar": "application/x-rar-compressed",
        "bin": "application/octet-stream",
        "wasm": "application/wasm",
        "jar": "application/java-archive",
        "epub": "application/epub+zip",
        "ods": "application/vnd.oasis.opendocument.spreadsheet",
        "odp": "application/vnd.oasis.opendocument.presentation",
    }
)

_MIME_TYPES_BY_BASENAME: Mapping[str, str] = MappingProxyType(
    {
        "cmakelists.txt": "text/x-cmake",
        "dockerfile": "text/x-dockerfile",
        "makefile": "text/x-makefile",
    }
)


def guess_mime_type(path: str | os.PathLike[str]) -> str | None:
    """Prefer MeshAgent's MIME mappings, then use the platform fallback."""

    normalized = os.fspath(path).split("?", maxsplit=1)[0].split("#", maxsplit=1)[0]
    filename = normalized.replace("\\", "/").rsplit("/", maxsplit=1)[-1].lower()
    if filename in _MIME_TYPES_BY_BASENAME:
        return _MIME_TYPES_BY_BASENAME[filename]
    if "." not in filename:
        return mimetypes.guess_type(normalized)[0]
    extension = filename.rsplit(".", maxsplit=1)[-1]
    return MIME_TYPES_BY_EXTENSION.get(extension) or mimetypes.guess_type(normalized)[0]
